# --- UOSC Bindings ---
SPACE        cycle pause; script-binding uosc/flash-pause-indicator
m            no-osd cycle mute; script-binding uosc/flash-volume
RIGHT        seek  5
LEFT         seek -5
Shift+RIGHT  seek  30; script-binding uosc/flash-timeline
Shift+LEFT   seek -30; script-binding uosc/flash-timeline
MENU         script-binding uosc/menu
MBTN_RIGHT   script-binding uosc/menu
TAB          script-binding uosc/toggle-ui
Ctrl+o       script-binding uosc/open-file

# --- Extra Utils ---
s            screenshot
